### PR TITLE
Use bytecheck to deserialize safely

### LINKED ISSUE #35: Use `bytecheck` crate for `world.query` and `world.transact`
**Describe what you want implemented** 
At the moment, it's possible to segfault the vm by providing an erroneous return type. In order to fix this, we should use the `bytecheck` crate for the return value when deserializing.

**Describe "Why" this is needed**
It should not be possible to crash the vm without unsafe.

### PR DESCRIPTION
**Pull request by krl**
fixes #35

### CODE REVIEW

File: dallo/src/helpers.rs [hunk 1]
```diff
@@ -4,31 +4,27 @@
...
 
-use crate::SCRATCH_BUF_BYTES;
-
+use crate::{StandardDeserialize, SCRATCH_BUF_BYTES};
 use rkyv::ser::serializers::{
     BufferScratch, BufferSerializer, CompositeSerializer,
 };
 use rkyv::ser::Serializer;
-use rkyv::{archived_root, Archive, Deserialize, Serialize};
+use rkyv::{check_archived_root, Archive, Deserialize, Serialize};
```
Comment (ZER0) [inline dallo/src/helpers.rs:12]: Unless there is a specific reason, it usually in Rust it's more idiomatic having `checked` / `unchecked` as suffix instead of prefix (see the standard library for example).

Comment (krl) [reply dallo/src/helpers.rs:12]: This is the name in `rkyv`, not something we control.

File: dallo/src/types.rs [hunk 2]
```diff
@@ -5,10 +5,33 @@
...
+
+pub trait StandardDeserialize<T>:
+    Deserialize<T, Infallible> + for<'a> CheckBytes<DefaultValidator<'a>>
+{
+}
+
+impl<T, U> StandardDeserialize<T> for U where
+    U: Deserialize<T, Infallible> + for<'a> CheckBytes<DefaultValidator<'a>>
+{
+}
```
Comment (ureeves) [inline dallo/src/types.rs:33]: Consider not introducing this wrapper trait. The user will still have to just implement `Deserialize<_, Infallible>` and `CheckBytes<DefaultValidator<_>>`.

**Review by ureeves — APPROVED** [review]
Looks good. I would consider removing the wrapper trait below, but maybe that's just me.
